-- ============================================================
--  01_schema.sql
--  Схемы БД для QA Automation Interview Trainer
--  Две схемы: ecommerce + banking
--  Запускается ПЕРВЫМ (до 02_seed.sql)
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ================= ECOMMERCE =================
CREATE SCHEMA IF NOT EXISTS ecommerce;
SET search_path TO ecommerce;

CREATE TABLE client (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    email      VARCHAR(200) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE address (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client(id),
    city      VARCHAR(100) NOT NULL,
    street    VARCHAR(200) NOT NULL,
    zip       VARCHAR(20)
);

CREATE TABLE shipping_type (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50)   NOT NULL,
    price NUMERIC(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE product (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(200)  NOT NULL,
    price NUMERIC(10,2) NOT NULL
);

-- order — зарезервированное слово, всегда в кавычках "order"
CREATE TABLE "order" (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id           BIGINT NOT NULL REFERENCES client(id),
    shipping_address_id BIGINT REFERENCES address(id),
    shipping_type_id    BIGINT REFERENCES shipping_type(id),
    status              VARCHAR(30)   NOT NULL,
    sum                 NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE order_product (
    order_id   BIGINT NOT NULL REFERENCES "order"(id),
    product_id BIGINT NOT NULL REFERENCES product(id),
    count      INT           NOT NULL CHECK (count > 0),
    price      NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (order_id, product_id)
);

CREATE INDEX idx_order_client     ON "order"(client_id);
CREATE INDEX idx_order_status     ON "order"(status);
CREATE INDEX idx_address_client   ON address(client_id);
CREATE INDEX idx_orderprod_product ON order_product(product_id);


-- ================= BANKING =================
CREATE SCHEMA IF NOT EXISTS banking;
SET search_path TO banking;

CREATE TABLE users (
    id         UUID PRIMARY KEY,
    full_name  VARCHAR(200) NOT NULL,
    email      VARCHAR(200) UNIQUE NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE / BLOCKED
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE accounts (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users(id),
    balance    NUMERIC(18,2) NOT NULL DEFAULT 0,
    currency   CHAR(3)       NOT NULL,                  -- RUB / USD / EUR
    status     VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE', -- ACTIVE / FROZEN / CLOSED
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE transactions (
    id                     UUID PRIMARY KEY,
    source_account_id      UUID NOT NULL REFERENCES accounts(id),
    destination_account_id UUID NOT NULL REFERENCES accounts(id),
    amount                 NUMERIC(18,2) NOT NULL CHECK (amount > 0),
    currency               CHAR(3)       NOT NULL,
    status                 VARCHAR(20)   NOT NULL,      -- PENDING / COMPLETED / FAILED
    idempotency_key        VARCHAR(100),
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
-- ВНИМАНИЕ: уникальный индекс на idempotency_key намеренно НЕ ставим,
-- чтобы воспроизвести баг с дублями (BUG-8). В проде он должен быть UNIQUE.

CREATE TABLE payment_templates (
    id                     UUID PRIMARY KEY,
    user_id                UUID NOT NULL REFERENCES users(id),
    name                   VARCHAR(200) NOT NULL,
    destination_account_id UUID NOT NULL REFERENCES accounts(id),
    amount                 NUMERIC(18,2) NOT NULL,
    currency               CHAR(3)       NOT NULL,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE outbox_events (
    id           UUID PRIMARY KEY,
    aggregate_id UUID         NOT NULL,
    event_type   VARCHAR(100) NOT NULL,
    payload      JSONB        NOT NULL,
    processed    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tx_source       ON transactions(source_account_id);
CREATE INDEX idx_tx_dest         ON transactions(destination_account_id);
CREATE INDEX idx_tx_status       ON transactions(status);
CREATE INDEX idx_tx_idem         ON transactions(idempotency_key);
CREATE INDEX idx_accounts_user   ON accounts(user_id);
CREATE INDEX idx_outbox_processed ON outbox_events(processed);
